#include "bufferscreen.h"

void welcome(){
    system("clear");
	printf("                                                           \n");
    printf("                                                           \n");             
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("      + + +         // - ` . .                             \n");
    printf("                     ` ` - : o +o + o +     / / / /        \n");
    printf("         + oo o o : : : + = - . o s s o o o                \n");
    printf("             ` ` - + +s s s- -- +o - o+ :- / s o+ / --     \n");
    printf("          `  o  `` ` s ss s s  o o                         \n");
    printf("                    s  o o` ` `   a ` ` os o o  / `        \n");
    printf("            -  : :  o : s                                  \n");
    printf("                   + o o oo . ` ` + o = +  s s s o         \n");
    printf("               - o + ` / s s                               \n");
    printf("                              / .. + . / s ss              \n");
    printf("                         s.   o s                          \n");
    printf("                                       `:`                 \n");
    printf("                                                           \n");  
    sleep(1); 
    system("clear");
    
    printf("                                                           \n");
    printf("                                                           \n");                
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                .:+++       //-`..                         \n");
    printf("                           ``-:o+o+o+  /////o+/:..         \n");
    printf("             ``-+oooo:::+=-.ossooo++=:                     \n");
    printf("                         ``-++sss---+o-o+:-/so+/--         \n");
    printf("             ``-+ooo```sssssssooo++-`                      \n");
    printf("                          `.:+soo```oo0a``osoo/`           \n");
    printf("              -+ooo:::==o:ssssss                           \n");
    printf("                             +oooo.``+o=+ssso              \n");
    printf("                  yyyo--o+`/ss                             \n");
    printf("                                 /..+./sss                 \n");
    printf("                       s. os                               \n");
    printf("                                    `:`                    \n");
    printf("                                                           \n");  
    sleep(1); 
    system("clear");
    
    printf("                                                           \n");
    printf("                                                           \n");           
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                 .:+++       //-`..                        \n");
    printf("                          ``-:o+o+o+  /////o+/:..          \n");
    printf("              ``-+oooo:::+=-.ossooo++=:                    \n");
    printf("                        ``-++sss---+o-o+:-/so+/--          \n");
    printf("              ``-+ooo```sssssssooo++-`                     \n");
    printf("                         `.:+soo```oo0a``osoo/`            \n");
    printf("               -+ooo:::==o:ssssss                          \n");
    printf("                            +oooo.``+o=+ssso               \n");
    printf("                    yyyo--o+`/ss                           \n");
    printf("                                /..+./sss                  \n");
    printf("                        s. os                              \n");
    printf("                                   `:`                     \n");
    printf("                                                           \n");  
    printf("                             W  E  L                       \n");
    sleep(1); 
    system("clear");
    
    printf("                                                           \n");
    printf("                                                           \n");                
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                  .:+++       //-`..                       \n");
    printf("                         ``-:o+o+o+  /////o+/:..           \n");
    printf("               ``-+oooo:::+=-.ossooo++=:                   \n");
    printf("                       ``-++sss---+o-o+:-/so+/--           \n");
    printf("               ``-+ooo```sssssssooo++-`                    \n");
    printf("                        `.:+soo```oo0a``osoo/`             \n");
    printf("                -+ooo:::==o:ssssss                         \n");
    printf("                           +oooo.``+o=+ssso                \n");
    printf("                     yyyo--o+`/ss                          \n");
    printf("                               /..+./sss                   \n");
    printf("                         s. os                             \n");
    printf("                                  `:`                      \n");
    printf("                                                           \n");  
    printf("                      W  E  L  C  O  M  E                  \n");
    sleep(1); 
    system("clear");
    

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                    .:+++       //-`..                     \n");
    printf("                       ``-:o+o+o+  /////o+/:..             \n");
    printf("                 ``-+oooo:::+=-.ossooo++=:                 \n");
    printf("                     ``-++sss---+o-o+:-/so+/--             \n");
    printf("                 ``-+ooo```sssssssooo++-`                  \n");
    printf("                      `.:+soo```oo0a``osoo/`               \n");
    printf("                  -+ooo:::==o:ssssss                       \n");
    printf("                         +oooo.``+o=+ssso                  \n");
    printf("                       yyyo--o+`/ss                        \n");
    printf("                             /..+./sss                     \n");
    printf("                           s. os                           \n");
    printf("                                `:`                        \n");
    printf("                                                           \n");  
    printf("                 W  E  L  C  O  M  E                       \n");
    sleep(1); 
    system("clear");
    
    
    printf("                                                           \n");
    printf("                                                           \n");                
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                      .:+++       //-`..                   \n");
    printf("                    ``-:o+o+o+  /////o+/:..                \n");
    printf("                   ``-+oooo:::+=-.ossooo++=:               \n");
    printf("                   ``-++sss---+o-o+:-/so+/--               \n");
    printf("                   ``-+ooo```sssssssooo++-`                \n");
    printf("                    `.:+soo```oo0a``osoo/`                 \n");
    printf("                      -+ooo:::==o:ssssss                   \n");
    printf("                       +oooo.``+o=+ssso                    \n");
    printf("                         yyyo--o+`/ss                      \n");
    printf("                           /..+./sss                       \n");
    printf("                             s. os                         \n");
    printf("                              `:`                          \n");
    printf("                                                           \n");  
    printf("                 W  E  L  C  O  M  E    T  O               \n");
    sleep(1); 
    system("clear");
    

    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                     `.:+++/       `-`````` `              \n");
    printf("                  ````-:o+o+o+  /////o+/:...``             \n");
    printf("                 ````-+oooo:::+=-.ossooo++=:-``            \n");
    printf("                 ````-++sss---+o-o+:-/so+/--```            \n");
    printf("                   ` .-+ooo```sssssssooo++-```             \n");
    printf("                  `.`.:+soo```oo0a``osoo/-```              \n");
    printf("                    `.-+ooo:::==o:ssss+/````               \n");
    printf("                      /+oooo.``+o=+sssoss+'                \n");
    printf("                        yyyyo--o+`/sssss-                   \n");
    printf("                          s/..+./sssos                     \n");
    printf("                           sss. ossss                      \n");
    printf("                              .`://                        \n");
    printf("                                                           \n");  
    printf("                 W  E  L  C  O  M  E    T  O               \n");
    printf("                                                           \n\n");    
    sleep(1); 
    system("clear");
    

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                      `.s-              `  `               \n");
    printf("                     `.:+++///     `-`````` ```            \n");
    printf("                  ````-:o+o...  /////o+/:...``             \n");
    printf("                 ````-+oooo:::+=-.ossooo+:- ````           \n");
    printf("                 ````-++sss---  -o+:-/so+/-..``            \n");
    printf("                   ` .-+ooo```sssssssooo++-````            \n");
    printf("                  `.`.:+soo```oo0a``osoo/-````             \n");
    printf("                    `.-+ooo:::   :ssss+/.```               \n");
    printf("                     -/+oooo.``  +sssoss+''                \n");
    printf("                       yyyyyo-- `/ssssso/-                 \n");
    printf("                         ss/.. ./sssos/-                   \n");
    printf("                          ssss. ossssss                    \n");
    printf("                            //.`:////                      \n");
    printf("                                                           \n");   
    printf("                 W  E  L  C  O  M  E    T  O               \n");
    printf("                        C  H  E                            \n\n");
    sleep(1); 
    system("clear");
    

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                     .-o-.                                 \n");
    printf("                    ` `.s-              `  `  `            \n");
    printf("                  `` `.:+++/       `-`````` ``````         \n");
    printf("                 `````-:o+o...      /o+/:...  `````        \n");
    printf("                 ````-+oooo:::   .ossooo+:- `` ``          \n");
    printf("                  ```-++sss---  -o+:-/so+/-..`````         \n");
    printf("                   ` .-+ooo```      -ooo++-`` ``           \n");
    printf("                  `.`.:+soo```   .+oosoo/-`` ``            \n");
    printf("                    `.-+ooo:::   :ssss+/.```               \n");
    printf("                     -/+oooo.``  +sssoss+                  \n");
    printf("                      yyyyyyo-- `/ssssso/-                 \n");
    printf("                       soss/.. ./sssos/-.                  \n");
    printf("                        ssssss. osssssss                   \n");
    printf("                         /////.`://///                     \n");
    printf("                                                           \n");                              
    printf("                 W  E  L  C  O  M  E    T  O               \n");
    printf("                        C  H  E  S  S                      \n\n");
    sleep(1); 
    system("clear");
    

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                      .-o-.                                \n");
    printf("                     ``.s-                                 \n");
    printf("                   ```.:+++/            ``                 \n");
    printf("                  ````-:o+o.       `-`````````             \n");
    printf("                    ``-/+++        /o+/:...  ``            \n");
    printf("                   ``-+oooo:     .ossooo+:- ``             \n");
    printf("                   ``-++sss-    -o+:-/so+/-..``            \n");
    printf("                    `.-+ooo`        -ooo++-```             \n");
    printf("                    `.:+soo`      .+oosoo/-``              \n");
    printf("                     .-+ooo:     :sssoss+/.`               \n");
    printf("                    --/+oooo.`   +sssosss+`                \n");
    printf("                   .osyyyyyyo-  `/sssssso/-`               \n");
    printf("                   .-+ossoss/.  ./sssoso/-.`               \n");
    printf("                   +ssssssssss. osssssssso/-               \n");
    printf("                   ://////////.`://////////.               \n");
    printf("                                                            \n");                              
    printf("                 W  E  L  C  O  M  E    T  O               \n");
    printf("               C  H  E  S  S    M  U  L                   \n\n");
    sleep(1); 
    system("clear");
    
    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                     `.-o-.                                \n");
    printf("                     ``.s-                                 \n");
    printf("                  ````.:+++/            ` `                \n");
    printf("                  ````-:o+o.       `-````````` `           \n");
    printf("                  ` ``-/+++        /o+/:...  ```           \n");
    printf("                  ```-+oooo:     .ossooo+:- ```            \n");
    printf("                  ```-++sss-    -o+:-/so+/-..```           \n");
    printf("                   ``.-+ooo`        -ooo++-```             \n");
    printf("                   ``.:+soo`      .+oosoo/-```             \n");
    printf("                    `.-+ooo:     :sssoss+/.``              \n");
    printf("                  ` --/+oooo.`   +sssosss+``               \n");
    printf("                  `.osyyyyyyo-  `/sssssso/-``              \n");
    printf("                   .-+ossoss/.  ./sssoso/-.``              \n");
    printf("                  `+ssssssssss. osssssssso/-`              \n");
    printf("                  `://////////.`://////////.               \n");
    printf("                                                            \n");                              
    printf("                 W  E  L  C  O  M  E    T  O               \n");
    printf("               C  H  E  S  S    M  U  L  T  I             \n\n");
    sleep(1); 
    system("clear");
    
    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                     `.-o-.                                \n");
    printf("                    ` `.s-                                 \n");
    printf("                 ``` `.:+++/            `  `               \n");
    printf("                  ````-:o+o.       `-`````` ``` `          \n");
    printf("                 `  ``-/+++        /o+/:...  `` `          \n");
    printf("                  ` `-+oooo:     .ossooo+:- `` `           \n");
    printf("                  ```-++sss-    -o+:-/so+/-..`` `          \n");
    printf("                 ` ` .-+ooo`        -ooo++-`` `            \n");
    printf("                  `.`.:+soo`      .+oosoo/-`` `            \n");
    printf("                    `.-+ooo:     :sssoss+/.` `             \n");
    printf("                 `  --/+oooo.`   +sssosss+` `              \n");
    printf("                  `.osyyyyyyo-  `/sssssso/-``              \n");
    printf("                   .-+ossoss/.  ./sssoso/-.``              \n");
    printf("                  `+ssssssssss. osssssssso/-`              \n");
    printf("                  `://////////.`://////////.               \n");
    printf("                                                            \n");                              
    printf("                 W  E  L  C  O  M  E    T  O               \n");
    printf("       C  H  E  S  S    M  U  L  T  I  P  L  A            \n\n");
    sleep(1); 
    system("clear");

    printf("                                                           \n");
    printf("                 `      :                                  \n");                               
    printf("             `     ` `.-o-.                                \n");
    printf("           `   ``   ` `.s-                                 \n");
    printf("             `   ``` `.:+++/            `  `  `            \n");
    printf("           `   `  ````-:o+o.       `-`````` `````   `      \n");
    printf("                 `  ``-/+++        /o+/:...  ```` `        \n");
    printf("             `    ` `-+oooo:     .ossooo+:- `` ` `         \n");
    printf("                  ```-++sss-    -o+:-/so+/-..````  `       \n");
    printf("                 ` ` .-+ooo`        -ooo++-`` ` `          \n");
    printf("                  `.`.:+soo`      .+oosoo/-`` `   `        \n");
    printf("                    `.-+ooo:     :sssoss+/.` ` `           \n");
    printf("                 `  --/+oooo.`   +sssosss+` `              \n");
    printf("                  `.osyyyyyyo-  `/sssssso/-``   `          \n");
    printf("                   .-+ossoss/.  ./sssoso/-.`` `            \n");
    printf("                  `+ssssssssss. osssssssso/-`              \n");
    printf("                  `://////////.`://////////.               \n");
    printf("                                                            \n");                              
    printf("                 W  E  L  C  O  M  E    T  O               \n");
    printf("       C  H  E  S  S    M  U  L  T  I  P  L  A  Y  E  R    \n\n");
}

void mainscreen(){
    printf("##################################################################\n\n");
    printf("       _________ __     __ ________  ________ ________    __      \n");
    printf("      /   ______|  |   |  |  ______|/  ______/  ______|  |  |     \n");
    printf("      |  |      |  |___|  |  |__   |  (_____ |  (_____   |  |     \n");
    printf("      |  |      |   ___   |   __|   \\_____   \\______  \\  |__| \n");  
    printf("      |  |______|  |   |  |  |_____  _____)  | _____)  |  __      \n");
    printf("      \\_________|__|   |__|________|/________/________/  |__|   \n\n");
    printf("                                                       (v.0.2)    \n");
    printf("##################################################################\n\n");
    printf("               **WELCOME TO CHESS KACANG BUNCHESS**               \n");
    printf("_________________________________________________________________\n");
    printf("|                                                               |\n");
    printf("|                          <(N)ew Game>                         |\n");
    printf("|                         <(L)oad Game>                         |\n");
    printf("|                        <Leader(B)oards>                       |\n");
    printf("|                           <(E)xit>                            |\n");
    printf("|_______________________________________________________________|  \n");
}

void eksit(){
    system("clear");
    printf("                                                           \n");
    printf("                 `      :                                  \n");                               
    printf("             `     ` `.-o-.                                \n");
    printf("           `   ``   ` `.s-                                 \n");
    printf("             `   ``` `.:+++/            `  `  `            \n");
    printf("           `   `  ````-:o+o.       `-`````` `````   `      \n");
    printf("                 `  ``-/+++        /o+/:...  ```` `        \n");
    printf("             `    ` `-+oooo:     .ossooo+:- `` ` `         \n");
    printf("                  ```-++sss-    -o+:-/so+/-..````  `       \n");
    printf("                 ` ` .-+ooo`        -ooo++-`` ` `          \n");
    printf("                  `.`.:+soo`      .+oosoo/-`` `   `        \n");
    printf("                    `.-+ooo:     :sssoss+/.` ` `           \n");
    printf("                 `  --/+oooo.`   +sssosss+` `              \n");
    printf("                  `.osyyyyyyo-  `/sssssso/-``   `          \n");
    printf("                   .-+ossoss/.  ./sssoso/-.`` `            \n");
    printf("                  `+ssssssssss. osssssssso/-`              \n");
    printf("                  `://////////.`://////////.               \n");
    printf("                                                            \n"); 
    sleep(1); 
    system("clear");

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                     `.-o-.                                \n");
    printf("                    ` `.s-                                 \n");
    printf("                 ``` `.:+++/            `  `               \n");
    printf("                  ````-:o+o.       `-`````` ``` `          \n");
    printf("                 `  ``-/+++        /o+/:...  `` `          \n");
    printf("                  ` `-+oooo:     .ossooo+:- `` `           \n");
    printf("                  ```-++sss-    -o+:-/so+/-..`` `          \n");
    printf("                 ` ` .-+ooo`        -ooo++-`` `            \n");
    printf("                  `.`.:+soo`      .+oosoo/-`` `            \n");
    printf("                    `.-+ooo:     :sssoss+/.` `             \n");
    printf("                 `  --/+oooo.`   +sssosss+` `              \n");
    printf("                  `.osyyyyyyo-  `/sssssso/-``              \n");
    printf("                   .-+ossoss/.  ./sssoso/-.``              \n");
    printf("                  `+ssssssssss. osssssssso/-`              \n");
    printf("                  `://////////.`://////////.               \n");
    sleep(1); 
    system("clear");   
    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                     `.-o-.                                \n");
    printf("                     ``.s-                                 \n");
    printf("                  ````.:+++/            ` `                \n");
    printf("                  ````-:o+o.       `-````````` `           \n");
    printf("                  ` ``-/+++        /o+/:...  ```           \n");
    printf("                  ```-+oooo:     .ossooo+:- ```            \n");
    printf("                  ```-++sss-    -o+:-/so+/-..```           \n");
    printf("                   ``.-+ooo`        -ooo++-```             \n");
    printf("                   ``.:+soo`      .+oosoo/-```             \n");
    printf("                    `.-+ooo:     :sssoss+/.``              \n");
    printf("                  ` --/+oooo.`   +sssosss+``               \n");
    printf("                  `.osyyyyyyo-  `/sssssso/-``              \n");
    printf("                   .-+ossoss/.  ./sssoso/-.``              \n");
    printf("                  `+ssssssssss. osssssssso/-`              \n");
    printf("                  `://////////.`://////////.               \n");
    sleep(1); 
    system("clear");
    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                      .-o-.                                \n");
    printf("                     ``.s-                                 \n");
    printf("                   ```.:+++/            ``                 \n");
    printf("                  ````-:o+o.       `-`````````             \n");
    printf("                    ``-/+++        /o+/:...  ``            \n");
    printf("                   ``-+oooo:     .ossooo+:- ``             \n");
    printf("                   ``-++sss-    -o+:-/so+/-..``            \n");
    printf("                    `.-+ooo`        -ooo++-```             \n");
    printf("                    `.:+soo`      .+oosoo/-``              \n");
    printf("                     .-+ooo:     :sssoss+/.`               \n");
    printf("                    --/+oooo.`   +sssosss+`                \n");
    printf("                   .osyyyyyyo-  `/sssssso/-`               \n");
    printf("                   .-+ossoss/.  ./sssoso/-.`               \n");
    printf("                   +ssssssssss. osssssssso/-               \n");
    printf("                   ://////////.`://////////.               \n");
    sleep(1); 
    system("clear");

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                     .-o-.                                 \n");
    printf("                    ` `.s-              `  `  `            \n");
    printf("                  `` `.:+++/       `-`````` ``````         \n");
    printf("                 `````-:o+o...      /o+/:...  `````        \n");
    printf("                 ````-+oooo:::   .ossooo+:- `` ``          \n");
    printf("                  ```-++sss---  -o+:-/so+/-..`````         \n");
    printf("                   ` .-+ooo```      -ooo++-`` ``           \n");
    printf("                  `.`.:+soo```   .+oosoo/-`` ``            \n");
    printf("                    `.-+ooo:::   :ssss+/.```               \n");
    printf("                     -/+oooo.``  +sssoss+                  \n");
    printf("                      yyyyyyo-- `/ssssso/-                 \n");
    printf("                       soss/.. ./sssos/-.                  \n");
    printf("                        ssssss. osssssss                   \n");
    printf("                         /////.`://///                     \n");
    sleep(1); 
    system("clear");

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                      `.s-              `  `               \n");
    printf("                     `.:+++///     `-`````` ```            \n");
    printf("                  ````-:o+o...  /////o+/:...``             \n");
    printf("                 ````-+oooo:::+=-.ossooo+:- ````           \n");
    printf("                 ````-++sss---  -o+:-/so+/-..``            \n");
    printf("                   ` .-+ooo```sssssssooo++-````            \n");
    printf("                  `.`.:+soo```oo0a``osoo/-````             \n");
    printf("                    `.-+ooo:::   :ssss+/.```               \n");
    printf("                     -/+oooo.``  +sssoss+''                \n");
    printf("                       yyyyyo-- `/ssssso/-                 \n");
    printf("                         ss/.. ./sssos/-                   \n");
    printf("                          ssss. ossssss                    \n");
    printf("                            //.`:////                      \n");
    sleep(1); 
    system("clear");

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                     `.:+++/       `-`````` `              \n");
    printf("                  ````-:o+o+o+  /////o+/:...``             \n");
    printf("                 ````-+oooo:::+=-.ossooo++=:-``            \n");
    printf("                 ````-++sss---+o-o+:-/so+/--```            \n");
    printf("                   ` .-+ooo```sssssssooo++-```             \n");
    printf("                  `.`.:+soo```oo0a``osoo/-```              \n");
    printf("                    `.-+ooo:::==o:ssss+/````               \n");
    printf("                      /+oooo.``+o=+sssoss+'                \n");
    printf("                        yyyyo--o+`/sssss-                   \n");
    printf("                          s/..+./sssos                     \n");
    printf("                           sss. ossss                      \n");
    printf("                              .`://                        \n");
    printf ("                   B        y        e        !             ");
    sleep(1); 
    system("clear");

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                      .:+++       //-`..                   \n");
    printf("                    ``-:o+o+o+  /////o+/:..                \n");
    printf("                   ``-+oooo:::+=-.ossooo++=:               \n");
    printf("                   ``-++sss---+o-o+:-/so+/--               \n");
    printf("                   ``-+ooo```sssssssooo++-`                \n");
    printf("                    `.:+soo```oo0a``osoo/`                 \n");
    printf("                      -+ooo:::==o:ssssss                   \n");
    printf("                       +oooo.``+o=+ssso                    \n");
    printf("                         yyyo--o+`/ss                      \n");
    printf("                           /..+./sss                       \n");
    printf("                             s. os                         \n");
    printf("                              `:`                          \n");
    printf ("                    B      y      e      !                  ");
    sleep(1); 
    system("clear");

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                    .:+++       //-`..                     \n");
    printf("                       ``-:o+o+o+  /////o+/:..             \n");
    printf("                 ``-+oooo:::+=-.ossooo++=:                 \n");
    printf("                     ``-++sss---+o-o+:-/so+/--             \n");
    printf("                 ``-+ooo```sssssssooo++-`                  \n");
    printf("                      `.:+soo```oo0a``osoo/`               \n");
    printf("                  -+ooo:::==o:ssssss                       \n");
    printf("                         +oooo.``+o=+ssso                  \n");
    printf("                       yyyo--o+`/ss                        \n");
    printf("                             /..+./sss                     \n");
    printf("                           s. os                           \n");
    printf("                                `:`                        \n");
    printf ("                      B    y    e    !                      ");
    sleep(1); 
    system("clear");

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                  .:+++       //-`..                       \n");
    printf("                         ``-:o+o+o+  /////o+/:..           \n");
    printf("               ``-+oooo:::+=-.ossooo++=:                   \n");
    printf("                       ``-++sss---+o-o+:-/so+/--           \n");
    printf("               ``-+ooo```sssssssooo++-`                    \n");
    printf("                        `.:+soo```oo0a``osoo/`             \n");
    printf("                -+ooo:::==o:ssssss                         \n");
    printf("                           +oooo.``+o=+ssso                \n");
    printf("                     yyyo--o+`/ss                          \n");
    printf("                               /..+./sss                   \n");
    printf("                         s. os                             \n");
    printf("                                  `:`                      \n");
    printf ("                       B   y   e   !                        ");
    sleep(1); 
    system("clear");

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                 .:+++       //-`..                        \n");
    printf("                          ``-:o+o+o+  /////o+/:..          \n");
    printf("              ``-+oooo:::+=-.ossooo++=:                    \n");
    printf("                        ``-++sss---+o-o+:-/so+/--          \n");
    printf("              ``-+ooo```sssssssooo++-`                     \n");
    printf("                         `.:+soo```oo0a``osoo/`            \n");
    printf("               -+ooo:::==o:ssssss                          \n");
    printf("                            +oooo.``+o=+ssso               \n");
    printf("                    yyyo--o+`/ss                           \n");
    printf("                                /..+./sss                  \n");
    printf("                        s. os                              \n");
    printf("                                   `:`                     \n");
    printf("                                                           \n");  
    printf ("                        B  y  e  !                          ");
    sleep(1); 
    system("clear");

    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                .:+++       //-`..                         \n");
    printf("                           ``-:o+o+o+  /////o+/:..         \n");
    printf("             ``-+oooo:::+=-.ossooo++=:                     \n");
    printf("                         ``-++sss---+o-o+:-/so+/--         \n");
    printf("             ``-+ooo```sssssssooo++-`                      \n");
    printf("                          `.:+soo```oo0a``osoo/`           \n");
    printf("              -+ooo:::==o:ssssss                           \n");
    printf("                             +oooo.``+o=+ssso              \n");
    printf("                  yyyo--o+`/ss                             \n");
    printf("                                 /..+./sss                 \n");
    printf("                       s. os                               \n");
    printf("                                    `:`                    \n");
    printf("                                                           \n");  
    printf ("                           B y e !                          ");
    sleep(1); 
    system("clear");
     
    printf("                                                           \n");
    printf("                                                           \n");                               
    printf("                                                           \n");
    printf("                                                           \n");
    printf("                                                           \n");
    printf("      + + +         // - ` . .                             \n");
    printf("                     ` ` - : o +o + o +     / / / /        \n");
    printf("         + oo o o : : : + = - . o s s o o o                \n");
    printf("             ` ` - + +s s s- -- +o - o+ :- / s o+ / --     \n");
    printf("          `  o  `` ` s ss s s  o o                         \n");
    printf("                    s  o o` ` `   a ` ` os o o  / `        \n");
    printf("            -  : :  o : s                                  \n");
    printf("                   + o o oo . ` ` + o = +  s s s o         \n");
    printf("               - o + ` / s s                               \n");
    printf("                              / .. + . / s ss              \n");
    printf("                         s.   o s                          \n");
    printf("                                       `:`                 \n");
    printf("                                                           \n");
    sleep(1);
    system("clear");  
    printf ("Bye!\n");
}
